jdbc:
  query: |
    SELECT CONCAT(SRC_GROUP, '', '', SRC_KEY) AS GROUPKEY,
                     SRC_GROUP, SRC_KEY,
                     ACTION_CODE,
                     MAX(EVENT_TS) AS EVENT_TS
                     FROM DB_EVENTS
                     WHERE STATUS_CODE = '0'
                     GROUP BY SRC_GROUP, SRC_KEY, ACTION_CODE

  update: |
    UPDATE DB_EVENTS
    SET STATUS_CODE='1'
    WHERE CONCAT(SRC_GROUP, '', '', SRC_KEY) IN (:GROUPKEY)
  split: true
  max-rows-per-poll: 300

spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            requiredGroups: jdbc-event-processor
          destination: jdbc-event
      rabbit:
        bindings:
          output:
            binder: rabbit
            producer:
              autoBindDlq: true
              deadLetterExchange: DLX
              republishToDlq: true
              requeueRejected: false
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost/rdbms_to_geode?useLegacyDatetimeCode=false&serverTimezone=America/New_York
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"