
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
mysql:
  image: mysql:latest
  restart: always
  environment:
      MYSQL_ROOT_PASSWORD: "${DATASOURCE_PASSWORD}"
  expose:
      - "3306"
  ports:
      - "3306:3306"

locator:
  image: apachegeode/geode:latest
  hostname: locator
  mem_limit: 512m
  expose:
    - "10334"
    - "1099"
    - "7575"
  #  - "1024"
  ports:
    - "1099:1099"
    - "10334:10334"
    - "7575:7575"
    - "7070:7070"
  volumes:
    - ./geode-scripts/:/geode-scripts/
  command: /geode-scripts/gfshWrapper.sh

server:
  image: apachegeode/geode
  mem_limit: 2g
  links:
    - locator:locator
  expose:
#    - "8080"
    - "40404"
    - "1099"
  ports:
      - "40404:40404"
  volumes:
    - ./geode-scripts/:/geode-scripts/
  command: /geode-scripts/startServer.sh # --server-port=40404 --max-heap=1G
